spring:
  application:
    name: employeehub

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/employeehub}
    username: ${SPRING_DATASOURCE_USERNAME:employeehub}
    password: ${SPRING_DATASOURCE_PASSWORD:employeehub}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  seed:
    enabled: ${APP_SEED_ENABLED:true}

logging:
  level:
    com.hasanozer.employeehub: INFO
